workflow:
   rules:
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never
launch-runner:
  tags: [cml]
  image: iterativeai/cml:0-dvc2-base1
  script:
    - cml runner launch
      --cloud=aws
      --cloud-region=eu-central-1
      --cloud-type=p3.2xlarge
      --cloud-hdd-size=64
      --cloud-aws-security-group=
      --cloud-aws-subnet=
      --reuse-idle
      --labels=cml-gpu
      --log=debug
train-and-report:
  tags: [cml-gpu]
  needs: [launch-runner]
  image: iterativeai/cml:0-dvc2-base1-gpu
  script:
    - apt-get update
    - apt-get install libgl1
    - pip install -r requirements.txt
    - dvc pull
    - dvc repro
    - dvc push
    - cml ci
    - git fetch origin
    - git show origin/master:plots/metrics_test.png > metrics_test-master.png
    - git show origin/master:plots/MAP_50-95.png > MAP_50-95-master.png
    - git show origin/master:plots/generalized_focal_loss.png > generalized_focal_loss-master.png
    - git show origin/master:plots/box_loss.png > box_loss-master.png
    - git show origin/master:plots/classification_loss.png > classification_loss-master.png
    - git show origin/master:plots/confusion_matrix_normalized_test.png > confusion_matrix_normalized_test-master.png
    - git show origin/master:plots/confusion_matrix_normalized_validation.png > confusion_matrix_normalized_validation-master.png
    - git show origin/master:plots/confusion_matrix_test.png > confusion_matrix_test-master.png
    - git show origin/master:plots/confusion_matrix_validation.png > confusion_matrix_validation-master.png
    - |
      cat <<EOF > report.md
      # OCR YOLOV8
      ## Workspace vs. Master
      | Workspace | Master |
      |:---:|:---:|
      | ![Workspace](./plots/metrics_test.png "Workspace") | ![Master](./metrics_test-master.png "Master") |
      | ![Workspace](./plots/MAP_50-95.png "Workspace") | ![Master](./MAP 50-95-master.png "Master") |
      | ![Workspace](./plots/generalized_focal_loss.png "Workspace") | ![Master](./generalized_focal_loss-master.png "Master") |
      | ![Workspace](./plots/box_loss.png "Workspace") | ![Master](./box_loss-master.png "Master") |
      | ![Workspace](./plots/classification_loss.png "Workspace") | ![Master](./classification_loss-master.png "Master") |
      | ![Workspace](./plots/confusion_matrix_normalized_test.png "Workspace") | ![Master](./confusion_matrix_normalized_test-master.png "Master") |
      | ![Workspace](./plots/confusion_matrix_normalized_validation.png "Workspace") | ![Master](./confusion_matrix_normalized_validation-master.png "Master") |
      | ![Workspace](./plots/confusion_matrix_test.png "Workspace") | ![Master](./confusion_matrix_test-master.png "Master") |
      | ![Workspace](./plots/confusion_matrix_validation.png "Workspace") | ![Master](./confusion_matrix_validation-master.png "Master") |
      EOF
    - cml comment create report.md
    - git add plots/*
    - git add models/best.onnx
    - echo $CI_COMMIT_REF_NAME
    - if ! git diff-index --quiet HEAD --; then git commit -m "Update repo"; fi
    - git push origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip

