workflow:
   rules:
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never
launch-runner:
  tags: [cml]
  image: iterativeai/cml:0-dvc2-base1
  script:
    - cml runner launch
      --cloud=aws
      --cloud-region=eu-central-1
      --cloud-type=p3.2xlarge
      --cloud-hdd-size=64
      --cloud-aws-security-group=
      --cloud-aws-subnet=
      --reuse-idle
      --labels=cml-gpu
      --log=info
train-and-report:
  tags: [cml-gpu]
  needs: [launch-runner]
  image: iterativeai/cml:0-dvc2-base1-gpu
  script:
    - apt-get update -q
    - apt-get install libgl1 -q
    - pip install -r requirements.txt -q
    - dvc pull --run-cache --allow-missing
    - dvc config cache.type symlink
    - dvc repro
    - cml ci
    - git fetch origin
    - git show origin/master:evaluation_model/metric_acc/loss.png > loss-master.png
    - git show origin/master:evaluation_model/metric_acc/box_loss.png > box_loss-master.png
    - git show origin/master:evaluation_model/metric_acc/class_loss.png > class_loss-master.png
    - git show origin/master:evaluation_model/metric_acc/mean_iou.png > mean_iou-master.png
    - |
      cat <<EOF > report.md
      # OCR RetinaNet binary
      ## Workspace vs. Master
      | Workspace | Master |
      |:---:|:---:|
      | ![Workspace](./evaluation_model/metric_acc/loss.png "Workspace") | ![Master](./loss-master.png "Master") |
      | ![Workspace](./evaluation_model/metric_acc/box_loss.png "Workspace") | ![Master](./box_loss-master.png "Master") |
      | ![Workspace](./evaluation_model/metric_acc/class_loss.png "Workspace") | ![Master](./class_loss-master.png "Master") |
      | ![Workspace](./evaluation_model/metric_acc/mean_iou.png "Workspace") | ![Master](./mean_iou-master.png "Master") |
      ## Mean Average Precision
      $(cat info/mAP.txt)
      ## Dataset info
      $(cat info/dataset_info.txt)
      ## Characters occurrences
      $(cat info/characters_occurrences.txt)
      ## GPU info
      $(cat info/gpu_info.txt)
      EOF
    - cml comment create report.md
    - dvc push
    - git add fit_res/ocr_model.pb
    - git add -f evaluation_model/\*
    - git add -f info/\*
    - git add dvc.lock
    - git commit -m "Update plots, info and frozen_graph"
    - echo $CI_COMMIT_REF_NAME
    - git push origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip
